# @package _global_
defaults:
  - _self_
  - pde: burgers
  - model: gpt-4.1
  - method: repeated_sample

log_path: ../working_logs
# log_path: ../tmp_test

folder_name_suffix: ''
redirect_stdout: False
assigned_gpu: 1

working_folder: ${log_path}/${pde.name}/${pde.pde_setting_name}${folder_name_suffix}/${method.name}/${model.name}/${now:%Y-%m-%d-%H-%M-%S}/

root_dataset_folder: ../dataset/CodePDE  # Replace with your dataset path. Absolute path is recommended.

hydra:
  run:
    dir: ${working_folder}